Update compose scripts to support test again

diff --git a/compose b/compose
--- a/compose
+++ b/compose
@@ -2,36 +2,59 @@
 
 if [ $# -eq 0 ]
   then
-    echo "Usage: compose VERSION [dev|staging]"
+    echo "Usage: compose [dev|staging|test] VERSION"
     exit 1
 fi
 
-APP_VERSION=$1
-API_VERSION=`docker inspect -f '{{.Config.Labels.apiVersion}}' docker.isaacscience.org/isaac-app:$APP_VERSION`
-ENV=$2
+ENV=$1
+APP_VERSION=$2
 
+if [ $2 = "dev" ] || [ $2 = "staging" ] || [ $2 = "test" ] || [ $2 = "live" ]; then
+  echo "Environment is now first argument to this script. Sorry James."
+  echo "Usage: compose [dev|staging|test] VERSION"
+  exit 1
+fi
 shift 2
+
+if [ $1 = "create" ] || [ $1 = "exec" ] || [ $1 = "pull" ] || [ $1 = "push" ] || [ $1 = "run" ] || [ $1 = "start" ] || [ $1 = "up" ]; then
+  docker pull docker.isaacscience.org/isaac-app:$APP_VERSION
+  API_VERSION=`docker inspect -f '{{.Config.Labels.apiVersion}}' docker.isaacscience.org/isaac-app:$APP_VERSION`
+  docker pull docker.isaacscience.org/isaac-api:$API_VERSION
+else
+  API_VERSION=`docker inspect -f '{{.Config.Labels.apiVersion}}' docker.isaacscience.org/isaac-app:$APP_VERSION`
+fi 
 
 API_NAME=api-$ENV-$API_VERSION
 APP_NAME=app-$ENV-$APP_VERSION
 
+read -r -d '' PG_SERVICE << EOM
+pg-$ENV:
+    container_name: pg-$ENV
+    image: isaac-pg
+    volumes:
+      - pg-$ENV:/pgdata
+EOM
+
+
 if [ "$ENV" == "dev" ]; then
-  PG=pg-dev
+  : # Continue
 elif [ "$ENV" == "staging" ]; then
-  PG=pg-staging
+  : # Continue
 elif [ "$ENV" == "live" ]; then
-  echo "Cannot manage live deployment with this script any more. Please use compose-release-live."
+  echo "Cannot manage live deployment with this script any more. Please use compose-live."
   exit 1
 elif [ "$ENV" == "test" ]; then
-  echo "Cannot manage test deployment with this script any more. Please use compose-test."
-  exit 1
+  read -r -d '' PG_SERVICE << EOM
+pg-test:
+    container_name: pg-test
+    image: isaac-pg
+    volumes:
+      - /local/data/test-db-schema.sql:/docker-entrypoint-initdb.d/test-db-schema.sql
+EOM
 else
   echo "Must set environment to dev or staging."
   exit 1
 fi
-
-docker pull docker.isaacscience.org/isaac-app:$APP_VERSION
-docker pull docker.isaacscience.org/isaac-api:$API_VERSION
 
 cat << EOF | docker-compose -p dc-$APP_NAME -f - $@
 version: '2'
@@ -51,8 +74,8 @@ services:
     extra_hosts:
       - elasticsearch:$LOCAL_ELASTICSEARCH
       - local-smtp:$LOCAL_SMTP
-    external_links:
-      - $PG:postgres
+    links:
+      - pg-$ENV:postgres
     volumes:
       - /local/data/m2:/root/.m2:rw
       - /local/data/isaac-config/segue-config.$ENV.properties:/local/data/rutherford/conf/segue-config.properties:ro
@@ -67,18 +90,13 @@ services:
       driver: journald
       options:
         tag: isaac-api-$ENV
-  $PG:
-    container_name: $PG
-    image: isaac-pg
-    volumes:
-      - $PG:/pgdata
-    restart: always
+  $PG_SERVICE
 networks:
   default:
     external:
       name: isaac
 volumes:
-  $PG:
+  pg-$ENV:
     external: true
 
 EOF
